# Generated by Django 3.2.6 on 2021-11-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='cpassword',
        ),
    ]
