# Generated by Django 3.2.6 on 2021-11-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_registration_cpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
